import {proxy} from 'valtio';

const state = proxy({
  intro: false,
  color: '#353934',
  isLogoTexture: true,
  isFullTexture: false,
  frontDecal: '',
  backDecal: '',
  leftShoulderDecal: '',
  rightShoulderDecal: '',
  fullDecal: '',
  frontDecalPosition: [0, 0.04, 0.15],
  backDecalPosition: [0, 0.04, -0.15],
  leftShoulderDecalPosition: [-0.2, 0.23, 0.03],
  rightShoulderDecalPosition: [0.2, 0.23, 0.03],
  frontDecalScale: 0.15,
  backDecalScale: 0.15,
  leftShoulderDecalScale: 0.08,
  rightShoulderDecalScale: 0.08,
  designTarget: 'front',
  autoRotate: false,
  autoRotateSpeed: 0.45,
  animationPreset: 'static',
  animationIntensity: 0.5,
  cameraAutoRotate: false,
  cameraAutoRotateSpeed: 1,
  stageBackground: 'dark',
  acidWashIntensity: 0,
  puffPrintIntensity: 0,
  logoDragMode: false,
  isDecalDragging: false,
  modelUrl: '/shirt_baked.glb',
  modelFileName: 'shirt_baked.glb',
  isModelReady: false,
  exportSize: 'auto',
  exportQuality: 'fast',
  exportModelFormat: 'glb',
  autoCleanDarkBg: true,
  areDecalTexturesReady: true,
});

export default state;
